# The ignore file of test/performance/Dockerfile (BuildKit reads
# <Dockerfile>.dockerignore next to the Dockerfile given with --file).
# The paths are relative to the build context, the project directory.
# None of this is read by the nodes in the image.
performance_report/node_modules
performance_report/dist
_build/test/logs
.git
